# Generated by Django 4.2 on 2023-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_survey", "0004_alter_answer_answer_alter_question_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="order",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
